name: Generate Cyberpunk Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate cyberpunk snake (pink-green)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sinch1717
          outputs: |
            dist/snake-cyberpunk.svg
          color_snake: "#ff00ff" # Neon pink snake
          color_dots: "#39ff14" # Neon green grid dots
          color_bg: "#0a0a0a"   # Deep black background for contrast

      - name: Push animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
